### ISSUE TITLE
Update Raspian on Raspberry Pi

### ISSUE THREAD

**Issue by thinkh** [Reemh/lunamon#2]
Our raspian installation is outdated and must be updated.

1. [Update from Jessie to Stretch](https://www.raspberrypi.org/documentation/raspbian/updating.md)
2. [Update from Stretch to Buster](https://www.maketecheasier.com/upgrade-raspberry-pi-raspbian-buster/)

https://en.wikipedia.org/wiki/Raspbian

**Comment by thinkh** [comment]
We wanted to update from Jessie to Buster, which obviously broke our Raspian. Now me must setup a new Raspian image.

https://maker.pro/raspberry-pi/tutorial/how-to-install-raspbian-on-your-raspberry-pi-sd-card

**Comment by Reemh** [comment]
We had an issue yesterday and we couldn't finish the upgrade to Buster (after we jumped from jessie to that)
We also couldn't connect to the pi anymore :(

**Comment by Reemh** [comment]
downloading the `noobs` will take 5 hours 😒

**Comment by thinkh** [comment]
Download via Torrent was much faster.

**Comment by thinkh** [comment]
Done by following [this instructions](https://maker.pro/raspberry-pi/tutorial/how-to-install-raspbian-on-your-raspberry-pi-sd-card).
